import type { Elephant } from '@/types';

export const getMockElephants = (): Elephant[] => [
  {
    id: 'IN-KA-023',
    name: 'Tusker Raja',
    sex: 'Male',
    age_class: 'Adult',
    state: 'Karnataka',
    district: 'Chamarajanagar',
    reserve: 'Bandipur National Park',
    collared: true,
    collar_id: 'BNP-023-C',
    last_location: 'Bandipur National Park',
    coordinates: '11.6643° N, 76.6862° E',
    latitude: 11.6643,
    longitude: 76.6862,
    movement_distance: 12.4,
    battery: 78,
    signal: 'Strong',
    last_transmission: '15 min ago',
    status: 'Active',
    weight: 5200,
    health_status: 'Excellent',
    last_seen: '2024-01-15',
    conflicts: 0,
  },
  {
    id: 'IN-AS-008',
    name: null,
    sex: 'Female',
    age_class: 'Adult',
    state: 'Assam',
    district: 'Sonitpur',
    reserve: 'Kaziranga National Park',
    collared: true,
    collar_id: 'KNP-008-C',
    last_location: 'Kaziranga National Park',
    coordinates: '26.5775° N, 93.1711° E',
    latitude: 26.5775,
    longitude: 93.1711,
    movement_distance: 8.7,
    battery: 92,
    signal: 'Strong',
    last_transmission: '32 min ago',
    status: 'Active',
    weight: 3800,
    health_status: 'Good',
    last_seen: '2024-01-14',
    conflicts: 1,
  },
  {
    id: 'IN-WB-034',
    name: 'Matriarch Mala',
    sex: 'Female',
    age_class: 'Adult',
    state: 'West Bengal',
    district: 'Alipurduar',
    reserve: 'Jaldapara National Park',
    collared: false,
    collar_id: null,
    last_location: 'Jaldapara National Park',
    coordinates: '26.7311° N, 89.2844° E',
    latitude: 26.7311,
    longitude: 89.2844,
    movement_distance: null,
    battery: null,
    signal: null,
    last_transmission: null,
    status: 'Active',
    weight: 4200,
    health_status: 'Good',
    last_seen: '2024-01-13',
    conflicts: 0,
  }
];