import type { Tiger } from '@/types';

export const getMockTigers = (): Tiger[] => [
  {
    id: 'IN-MP-045',
    name: 'Collarwali',
    sex: 'Female',
    age_class: 'Adult',
    state: 'Madhya Pradesh',
    district: 'Seoni',
    reserve: 'Pench Tiger Reserve',
    stripe_match_id: 'SM-2024-045',
    confidence: 98.5,
    image_count: 47,
    last_seen: '2024-01-15',
    status: 'Alive',
    collared: true,
    collar_id: 'PTR-045-C',
    battery: 85,
    signal: 'Strong',
    conflicts: 0,
    coordinates: '21.7679° N, 79.2961° E',
    latitude: 21.7679,
    longitude: 79.2961,
  },
  {
    id: 'IN-RJ-012',
    name: 'T-91',
    sex: 'Male',
    age_class: 'Adult',
    state: 'Rajasthan',
    district: 'Sawai Madhopur',
    reserve: 'Ranthambore',
    stripe_match_id: 'SM-2024-012',
    confidence: 95.2,
    image_count: 123,
    last_seen: '2024-01-14',
    status: 'Monitoring',
    collared: true,
    collar_id: 'RTR-012-C',
    battery: 62,
    signal: 'Medium',
    conflicts: 2,
    coordinates: '26.0173° N, 76.5026° E',
    latitude: 26.0173,
    longitude: 76.5026,
  },
  {
    id: 'IN-KA-078',
    name: 'Bandipur Male',
    sex: 'Male',
    age_class: 'Sub-adult',
    state: 'Karnataka',
    district: 'Chamarajanagar',
    reserve: 'Bandipur National Park',
    stripe_match_id: 'SM-2024-078',
    confidence: 92.8,
    image_count: 34,
    last_seen: '2024-01-13',
    status: 'Alive',
    collared: false,
    collar_id: null,
    battery: null,
    signal: null,
    conflicts: 1,
    coordinates: '11.6643° N, 76.6862° E',
    latitude: 11.6643,
    longitude: 76.6862,
  }
];